config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope format: false do
    get '/elb_status', to: 'site#elb_status'

    devise_for :users, :controllers => {
      :omniauth_callbacks => "login"
    }

    get '/login', to: 'login#urs'

    # https://github.com/plataformatec/devise/issues/1390
    devise_scope :user do
      root to: "devise/sessions#new"
      get '/session/new' => 'devise/sessions#new', as: :new_user_session
      get '/session/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
    end

    get '/home', to: 'site#home'
    get '/general_home', to: 'site#general_home'

    resources :collections do
      collection do
        put 'refresh'
      end
    end

    get '/collections_search', to: 'collections#search'

    get 'user/email_preferences' => 'user#email_preferences', as: 'email_preferences'
    post 'user/email_preferences/update' => 'user#update_email_preferences', as: 'update_email_preferences'

    resources :granules do
      member do
        delete "replace"
        post "pull_latest"
        post "ingest_specific"
      end
    end
    resources :comments
    resources :discussions
    resources :reviews do
      member do
        put "update_review_comment"
        put "update_report_comment"
      end
    end
    resources :records do
      member do
        get "copy_prior_recommendations"
        post "complete"
        post "associate_granule_to_collection"
      end

      collection do
        get "find_records_json"
        get "finished"
        get "navigate"
        put "allow_updates"
        put "stop_updates"
        post "revert"
        post "batch_complete"
        delete "hide"
        put "unhide"
      end
    end

    get '/record_refresh', to: 'records#refresh'
    get '/invalid_keywords/csv_report', to: 'invalid_keywords#csv_report'
    get '/invalid_keywords/sync', to: 'invalid_keywords#sync'
    get '/reports/home', to: 'reports#home'
    post '/reports/home', to: 'reports#home'
    get '/reports/provider', to: 'reports#provider'
    post '/reports/provider', to: 'reports#provider'
    get '/reports/search', to: 'reports#search'
    get '/reports/selection', to: 'reports#selection'
    post '/reports/selection', to: 'reports#selection'
    get '/reports/review', to: 'reports#review'
    post '/reports/review', to: 'reports#review'

    # https://stackoverflow.com/questions/21654826/how-to-rescue-page-not-found-404-in-rails
    # The “a” is actually a parameter in the Rails 3 Route Globbing technique. For example,
    # if your url was /this-url-does-not-exist, then params[:a] equals “/this-url-does-not-exist”.
    match '*a', :to => 'errors#routing', via: :get
  end
end

app/controllers/collection_controller.rb
class CollectionController < ApplicationController

  def show
    @concept_id = params["concept_id"]
    if !@concept_id
      flash[:error] = "No concept_id provided to find record details"
      redirect_to curation_home_path
    end

    collection = Collection.find_by(concept_id: @concept_id)
    @collection_records = collection.records.order(:revision_id).reverse_order

    @granule_objects = Granule.where(collection: collection)
    # @granule_records = granule_objects.map { |granule|}
  end

  def search
    @search_iterator, @collection_count = Cmr.collection_search(params["free_text"], params["provider"], params["curr_page"])
    @free_text = params["free_text"]
    @provider = params["provider"]
    @curr_page = params["curr_page"]
    @provider_select_list = provider_select_list
  end

  def new
    collection_data = Cmr.get_collection(params["concept_id"])
    @concept_id = collection_data["concept_id"]
    @revision_id = collection_data["revision_id"]
    @short_name = collection_data["Collection"]["ShortName"]

    @already_ingested = Collection.record_exists?(@concept_id, @revision_id)
    @granule_count = Cmr.collection_granule_count(@concept_id)
  end

  #this is a behemoth method, but it does several things
  #creates and saves collection record, all related granule records and ingests
  #runs evaluation script over collection record and all granules and saves results as comments
  def create
    concept_id = params["concept_id"]
    revision_id = params["revision_id"]

    if Collection.record_exists?(concept_id, revision_id)
      redirect_to curation_home_path
      flash[:alert] = 'This collection has already been ingested into the system'
      return
    end

    # begin 
      collection_data = Cmr.get_collection(concept_id)
      short_name = collection_data["Collection"]["ShortName"]
      ingest_time = DateTime.now
      #nil gets turned into 0
      granules_count = params["granulesCount"].to_i
      #finding parent collection
      collection_object = Collection.find_or_create_by(concept_id: concept_id, short_name: short_name)
      #creating collection record related objects
      new_collection_record = Record.new(recordable: collection_object, revision_id: revision_id, closed: false, rawJSON: collection_data.to_json)
      ingest_record = Ingest.new(record: new_collection_record, user: current_user, date_ingested: ingest_time)

      #returns a list of granule data
      granules_to_save = Cmr.random_granules_from_collection(concept_id, granules_count)
      #replacing the data with new granule & record & ingest objects
      granules_to_save.map! do |granule_data| 
        granule_object = Granule.new(concept_id: granule_data["concept_id"], collection: collection_object)
        new_granule_record = Record.new(recordable: granule_object, revision_id: granule_data["revision_id"], closed: false, rawJSON: granule_data.to_json)
        granule_ingest = Ingest.new(record: new_granule_record, user: current_user, date_ingested: ingest_time)
        [ granule_object, new_granule_record, granule_ingest ]
      end 

      #saving all the related collection and granule data in a combined transaction
      ActiveRecord::Base.transaction do
        new_collection_record.save!
        ingest_record.save!
        granules_to_save.flatten.each { |savable_object| savable_object.save! }
      end


      #getting list of records for script
      granule_records = granules_to_save.select { |savable_object| savable_object.is_a?(Record) }

      new_collection_record.evaluate_script
      granule_records.each do |record|
        record.evaluate_script
      end

      flash[:notice] = "The selected collection has been successfully ingested into the system"
    # rescue
      flash[:alert] = 'There was an error ingesting the record into the system'
    # end
      
    redirect_to curation_home_path
  end

  def review
    @concept_id = params["concept_id"]
    @revision_id = params["revision_id"]

    if !(@concept_id || @revision_id)
      flash[:error] = "Missing the concept_id or revision_id to Locate review"
      redirect_to curation_home_path
    end

    @collection_record = Collection.find_record(@concept_id, @revision_id)
    @record_comments = @collection_record.comments
    @user_comment = @record_comments.select { |comment| comment.user_id == current_user.id }
    @other_users_comments = @record_comments.select { |comment| (comment.user_id != current_user.id && comment.user_id != -1) }

    @script_comment = @record_comments.select { |comment| comment.user_id == -1 }.first

    if @script_comment
      @script_comment = JSON.parse(@script_comment.rawJSON)
    end

    if @user_comment.empty?
      @collection_record.add_comment(current_user.id)
      #grabbing the newly made comment
      @user_comment = Comment.where(user: current_user, record: @collection_record).first
    else
      @user_comment = @user_comment.first
    end

    @user_comment_contents = JSON.parse(@user_comment.rawJSON)

    @display_list = []

    JSON.parse(@collection_record.rawJSON)["Collection"].each do |key, value|
      if value.is_a?(String) 
        @display_list.push({key: key, value: value, script: @script_comment[key], reviewer: @user_comment_contents["Collection"][key]})
      end
    end

  end

end

app/helpers/collections_helper.rb
# frozen_string_literal: true

require 'action_view/helpers/javascript_helper'
require 'active_support/core_ext/array/access'
require 'active_support/core_ext/hash/keys'
require 'active_support/core_ext/string/output_safety'

module CollectionsHelper

  # indicator used by the view to tell the user if the granule has been deleted from cmr
  def indicator_for_granule_deleted_in_cmr(granule)
    granule.deleted_in_cmr ? '[Granule Not Found in CMR]' : ''
  end

  # indicator used by the view to tell the user if a new granule revision has come available in cmr.
  def indicator_for_has_new_granule_revision(granule)
    return '' if granule.deleted_in_cmr
    highest_revision_id = 0
    granule.records.each do |granule_record|
      revision_id = granule_record.revision_id.to_i
      highest_revision_id = revision_id if revision_id > highest_revision_id
    end
    if highest_revision_id < granule.latest_revision_in_cmr.to_i
      if can?(:create_granule, Collection)
        return link_to("Import New Revision #{granule.latest_revision_in_cmr}",
                     pull_latest_granule_path(granule.id),
                     method: :post, class: 'import_new_revision',
                     data: { confirm: 'Are you sure?' })
      else
        return content_tag('span', "[Latest Revision #{granule.latest_revision_in_cmr}]")
      end
    else
      return ''
    end
  end

  def link_for_edit_collection_in_mmt(concept_id)
    env_name = ENV.fetch('RAILS_ENV', '').downcase
    case env_name
    when 'sit', 'development', 'test'
      "https://mmt.sit.earthdata.nasa.gov/collections/#{concept_id}"
    when 'uat'
      "https://mmt.uat.earthdata.nasa.gov/collections/#{concept_id}"
    else
      "https://mmt.earthdata.nasa.gov/collections/#{concept_id}"
    end
  end

  def get_associated_granule_option(record)
    associated_granule_value = record.associated_granule_value

    if associated_granule_value.nil?
      'Undefined'
    elsif associated_granule_value == 'No Granule Review'
      'No Granule Review'
    else
      granule_record = Record.find_by id: associated_granule_value
      granule_record.nil? ? 'Undefined' : granule_record.id
    end
  end
end

app/views/collections/search.html.erb
<%= render(partial: 'shared/navigation', locals: {title: "METADATA CURATION: SEARCH"}) %>


<div class="search_page_box">
  <div class="space_box"></div>

    <div class="search_title">
      <p><strong>Search the CMR:</strong></p>
    </div>

    <%= form_with( url: collections_search_path, id: 'cmr_search', method: "get", local:true) do %>
      <%= select_tag(:provider,options_for_select(provider_select_list, :selected => params[:provider])) %>
      <%= text_field_tag(:free_text, params[:free_text]) %>
      <%= hidden_field_tag(:curr_page, "1") %>
      <%#= submit_tag("", class: 'search_button eui-icon eui-fa-search') %>
      <button class="search_button">
        <i class="eui-icon eui-fa-search"></i>
      </button>
    <% end %>

    <script type="text/javascript">
      document.getElementById('cmr_search').onsubmit = function() {
        showLoading("Searching the CMR");
      }
    </script>

    <br>
    <p><strong>Search Results:</strong></p>

    <div class="results_box">

      <div class="search_phrase">
        <p>Search Phrase = <%=params[:free_text]%></p>
      </div>
      <div class="total_results">
        <p>Total Results = <%= @collection_count %></p>
      </div>
      
    


      <% unless @search_iterator.nil? %>
        <% unless @search_iterator.empty? %>

            <table cellpadding="5" border="1">
                <tr>
                    <th>Results #</th>
                    <th>Concept_ID</th>
                    <th>Revision_ID</th>
                    <th>ShortName</th>
                    <th>Version</th>
                    <th>Selection</th>
                </tr>

                

              <% @search_iterator.each_with_index do |result, index| %>
                <tr>
                    <td><%= (params[:curr_page].to_i - 1) * 10 + index + 1 %></td>
                    <td id="concept<%= index.to_s %>"><%= result["concept_id"] %></td>
                    <td id="revision<%= index.to_s %>"><%= result["revision_id"] %></td>
                    <td><%= result["Collection"]["ShortName"] %></td>
                    <td id="version<%= index.to_s %>"><%= result["Collection"]["VersionId"] %></td>
                  <td><input type="radio" id="search<%= index.to_s %>" name="searchSelection" value="<%= index.to_s %>"/></td>
                </tr>
              <% end %>
            </table>

            <div class="bottom_row">
              <div class="select_collection">
                <%= form_with( url: new_collection_path , method: "get", id: 'ingest_form', local: true) do %>
                  <%= hidden_field_tag(:concept_id, "") %>
                  <%= hidden_field_tag(:revision_id, "") %>
                  <%= hidden_field_tag(:version_id, "") %>
                  <%= submit_tag("Select Collection", id: 'ingest_submit', class: 'selectButton') %>
                <% end %> 

                <script type="text/javascript">
                  document.getElementById('ingest_form').onsubmit = function() {
                    showLoading('Finding Record in CMR');
                  }
                </script>
              </div>

              <div class="direction_links">
                
                <% if params[:curr_page].to_i > 1 %>
                  <a href="<%=collections_search_path(free_text: params[:free_text], provider: params[:provider], curr_page: (params[:curr_page].to_i - 1).to_s)%>" id="prev_link">
                    <button id="prev_button">
                      <i class="eui-icon eui-fa-chevron-circle-left"></i>
                      <p>Previous Page</p>    
                    </button>
                  </a>

                  <script type="text/javascript">
                    document.getElementById('prev_link').onclick = function() {
                      showLoading('Loading');
                    }
                  </script>
                <% end %>
                
                <% if params[:curr_page].to_i * 10 < @collection_count %>
                  <a href="<%=collections_search_path(free_text: params[:free_text], provider: params[:provider], curr_page: (params[:curr_page].to_i + 1).to_s)%>" id="next_link">
                    <button id="next_button">
                      <p>Next Page</p>    
                      <i class="eui-icon eui-fa-chevron-circle-right"></i>
                    </button>
                  </a>

                  <script type="text/javascript">
                    document.getElementById('next_link').onclick = function() {
                      showLoading('Loading');
                    }
                  </script>
                <% end %>
              </div>

            </div>



            <script type="text/javascript">
                var ingestButton = document.getElementById("ingest_submit");
                ingestButton.disabled = true;

                var searchSelector = document.getElementsByName("searchSelection");

                for (var i = 0, length = searchSelector.length; i < length; i++) {
                    (function(index) {
                        var temp = document.getElementById("search" + i);
                        temp.onclick = function() {
                                              var count = index;
                                              updateSelection(count);
                                              ingestButton.disabled = false;
                                              }
                    })(i);
                }


            </script>



        <% end %>



      <% end %>



    </div>

</div>

<script type="text/javascript">



  var updateSelection = function(count) {
    var rowName = "concept" + count;
    var newConceptId = document.getElementById(rowName).innerHTML;
    document.getElementById("concept_id").value = newConceptId;

    var rowNameRevision = "revision" + count;
    var newRevisionId = document.getElementById(rowNameRevision).innerHTML;
    document.getElementById("revision_id").value = newRevisionId;

    var rowNameVersion = "version" + count;
    var newVersionId = document.getElementById(rowNameVersion).innerHTML;
    document.getElementById("version_id").value = newVersionId;

  }



</script>

app/views/collections/show.html.erb
<%= render(partial: 'shared/navigation', locals: {title: "METADATA CURATION: COLLECTION"}) %>

<div class="record_show_box">
  <div class="space_box"></div>

  <div class="record_show_header">
    <div class="collection_title">
      <h3>Concept ID: <%= @concept_id %></h3>
      <h3>Short Name: <%= @collection_records.first.recordable.short_name %></h3>
      <% if @collection_records.first.format == @collection_records.first.native_format %>
        <h3>Format: <span id="record_format"><%= get_format_and_version(@collection_records.first.format, @collection_records.first.format_version)%></span></h3>
      <% else %>
        <h3>Ingest Format: <%= @collection_records.first.format %></h3>
        <h3>Native Format: <%= @collection_records.first.native_format %></h3>
      <% end %>
    </div>

    <% if can?(:view_edit_in_mmt_link, @record.recordable) %>
      <div class="edit_collection_in_mmt_link">
        <%= link_to link_for_edit_collection_in_mmt(@concept_id), class: 'eui-btn--blue', target: '_blank', method: :get do %>
          <i class='fa fa-external-link'></i>&nbsp;&nbsp;EDIT COLLECTION IN MMT
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="space_box"></div>

  <div class="group_container">
    <div class="group_box left_box">

      <h3 class="collection_revision_header">Collection Revisions</h3>
      <% @collection_records.each_with_index do |record, index| %>

        <div id="collection_revision_<%= record.revision_id %>" class="collection_revision">
          <table class="revision_table">
            <tr>
              <th class="collection_granule_revision_row">
                <div class="collection_review_box">
                  <h4>Revision ID: <%= record.revision_id %></h4>
                  <% if can?(:associate_granule_to_collection, @collection) %>
                    <form id="form-<%= record.revision_id %>" accept-charset="UTF-8" action="<%= associate_granule_to_collection_record_path(record.id) %>" method="post">
                      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                      <h4>Granule Rev ID: <%= select_tag("associated_granule_value",
                                                         options_for_select(@associated_granules_options, get_associated_granule_option(record)), {class: "associated_granule_value", revision_id: "#{record.revision_id}"}) %>
                      </h4>
                    </form>
                  <% else %>
                    <h4>Revision ID: <%= record.associated_granule_value %></h4>
                  <% end %>
                </div>
              </th>
            </tr>

            <tr>
              <td>
                <table class="revision_review_table">
                  <tr>
                    <td>Reviewer</td>
                    <td>Status</td>
                    <td>Completion Date</td>
                  </tr>


                  <% record.reviews.each do |review| %>
                    <tr>
                      <td><%= review.user.email %></td>
                      <td><%= review.state_string %></td>
                      <td><%= review.formatted_date %></td>
                    </tr>

                  <% end %>
                </table>

                <div class="review_actions">

                  <div class="ingest_score">
                    <p>Collection Review Status: <%= record.closed? || record.finished? ? "Closed" : "In Process" %></p>
                  </div>
                  <div class="collection_revisions_button_container">
                    <div class ="see_review_details_button">
                      <%= button_to "See Collection Review Details", record_path(record.id), class: "smallSelectButton", method: :get %>
                    </div>
                    <div class ="see_review_details_button">
                      <%= button_to "Delete Collection", record_path(record.id), class: "deleteButton", method: :delete, data: { confirm: "Are you sure you want to delete this collection?" } %>
                    </div>
                  </div>
                </div>

              </td>
            </tr>

          </table>
        </div>

      <% end %>

    </div>

    <% if @granule_objects.count > 0 %>
      <div class="group_box">
        <div>
          <% if can?(:create_granule, @granule_objects.first.collection) %>
            <h3>
              Granules
              <div>
                <% modal_id = "ingest-specific-granule-modal-id" %>
                <%= button_to "Ingest New Random Granule", granules_path(:id => @granule_objects.first.collection.id), method: :post, class: "smallSelectButton ingest_buttons", id: "ingest_create", data: {confirm: "Are you sure?"} %>
                <input class="smallSelectButton confirm-modal-button ingest_buttons" type="button" id="ingest-specific-granule-modal" name="<%= modal_id %>" href="#<%= modal_id %>" value="Ingest Specific Granule"/>
              </div>

              <div id="<%= modal_id %>" class="eui-modal-content confirm-modal">
                <a href="#" class="modal-close float-r"><i class="fa fa-times"></i><span class="is-invisible">Close</span></a>
                <!-- Todo: Verify AuthenticityToken issue is fixed in RAILS 6.0 -->
                <!-- See CMRARC-484 and https://github.com/rails/rails/issues/24257-->
                <!-- During the RAILS 5.2 upgrade, there was an issue with the CSRF authenticity tokens.   Namely, this specific-->
                <!-- workflow:  if a user clicks See Review Details, then clicks Curation Home, then clicks Revert Record,-->
                <!-- they will get a Invalid Authenticity Token.   Workaround is to tell form_with it should not auto include the-->
                <!-- token, rather we should explicitly include it ourselves. -->
                <%= form_with( url: ingest_specific_granule_path(:id => @granule_objects.first.collection.id), method: "post", local:true, authenticity_token: false) do %>
                  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                  <p>
                    Enter Granule Concept ID: <input type="text" id="granule_concept_id" name="granule_concept_id" width="100px">
                  </p>
                  <input type="submit" value="OK" class="smallSelectButton confirm-no-button"> &nbsp;
                  <a href="#"><input type="button" class="smallSelectButton confirm-no-button" value="Cancel"/></a>
                <% end %>
              </div>
            </h3>
          <% else %>
            <h3 class="granules_revision_header">Granules</h3>
          <% end %>
        </div>
          <% @granule_records.each do |granule_record| %>
            <table id="granule_revision_<%= granule_record.revision_id %>" class="revision_table">
              <tr>
                <th class="collection_granule_revision_row">
                  <h4>
                    <div>Concept ID: <%= granule_record.concept_id %>
                      <span class="indicator_for_granule_deleted_in_cmr"><%= indicator_for_granule_deleted_in_cmr(granule_record.recordable) %></span>
                    </div>

                    <% if can?(:associate_granule_to_collection, @collection) %>
                      <div class="granule_revision" title="Drag revision over to associate with collection record." granule_option_id="<%= granule_record.id %>">Revision_ID: <%= granule_record.revision_id %>
                        <span class="indicator_for_has_new_granule_revision"><%= indicator_for_has_new_granule_revision(granule_record.recordable) %></span>
                      </div>
                    <% else %>
                      <div class="granule_revision_nodragdrop" granule_option_id="<%= granule_record.id %>">Revision_ID: <%= granule_record.revision_id %>
                        <span class="indicator_for_has_new_granule_revision"><%= indicator_for_has_new_granule_revision(granule_record.recordable) %></span>
                      </div>
                    <% end %>

                  </h4>
                </th>
              </tr>

              <tr>
                <td>
                  <table class="revision_review_table">
                    <tr>
                      <td>Reviewer</td>
                      <td>Status</td>
                      <td>Completion Date</td>
                    </tr>


                    <% granule_record.reviews.each do |review| %>
                      <tr>
                        <td><%= review.user.email %></td>
                        <td><%= review.state_string %></td>
                        <td><%= review.formatted_date %></td>
                      </tr>

                    <% end %>
                  </table>

                  <div class="review_actions">
                    <div class="ingest_score">
                      <p>Granule Review Status: <%= granule_record.closed? ? "Closed" : "In Process" %></p>
                    </div>

                    <div id="granule_review_link">
                      <%= button_to "See Granule Review Details", record_path(granule_record.id), class: "smallSelectButton", method: :get %>
                    </div>
                    <% if can?(:delete_granule, granule_record.recordable) %>&nbsp;
                      <% modal_id = "delete-granule-modal-id-#{granule_record.recordable_id}-#{granule_record.id}" %>
                      <input class="deleteButton confirm-modal-button" type="button" id="delete-granule-modal" name="<%= modal_id %>" href="#<%= modal_id %>" value="Delete Granule"/>

                      <div id="<%= modal_id %>" class="eui-modal-content confirm-modal">
                        <a href="#" class="modal-close float-r"><i class="fa fa-times"></i><span class="is-invisible">Close</span></a>
                        <p>
                          Are you sure you want to delete granule revision #<%= granule_record.revision_id %>?
                        </p>
                        <p>
                          <%= button_to "Yes", granule_path(granule_record.recordable_id, record_id: granule_record.id), method: :delete, class: 'smallSelectButton confirm-yes-button' %>&nbsp;
                          <a href="#"><input type="button" class="smallSelectButton confirm-no-button" value="No"/></a>
                        </p>
                        </p>
                      </div>
                    <% end %>
                  </div>
                </td>
              </tr>

            </table>
          <% end %>
      </div>
    <% else %>

      <div class="group_box">
        <div>
          <% if can?(:create_granule, @record.recordable) %>
            <h3>
              Granules
              <%= button_to "Ingest New Random Granule", granules_path(:id => @record.recordable.id), method: :post, class: "smallSelectButton", id: "ingest_create", form_class: "ingest_new_granule_button", data: {confirm: "Are you sure?"} %>
            </h3>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>