config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope format: false do
    get '/elb_status', to: 'site#elb_status'

    devise_for :users, :controllers => {
      :omniauth_callbacks => "login"
    }

    get '/login', to: 'login#urs'

    # https://github.com/plataformatec/devise/issues/1390
    devise_scope :user do
      root to: "devise/sessions#new"
      get '/session/new' => 'devise/sessions#new', as: :new_user_session
      get '/session/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
    end

    get '/home', to: 'site#home'
    get '/general_home', to: 'site#general_home'

    resources :collections do
      collection do
        put 'refresh'
      end
    end

    get '/collections_search', to: 'collections#search'

    get 'user/email_preferences' => 'user#email_preferences', as: 'email_preferences'
    post 'user/email_preferences/update' => 'user#update_email_preferences', as: 'update_email_preferences'

    resources :granules do
      member do
        delete "replace"
        post "pull_latest"
        post "ingest_specific"
      end
    end
    resources :comments
    resources :discussions
    resources :reviews do
      member do
        put "update_review_comment"
        put "update_report_comment"
      end
    end
    resources :records do
      member do
        get "copy_prior_recommendations"
        post "complete"
        post "associate_granule_to_collection"
      end

      collection do
        get "find_records_json"
        get "finished"
        get "navigate"
        put "allow_updates"
        put "stop_updates"
        post "revert"
        post "batch_complete"
        delete "hide"
        put "unhide"
      end
    end

    get '/record_refresh', to: 'records#refresh'
    get '/invalid_keywords/csv_report', to: 'invalid_keywords#csv_report'
    get '/invalid_keywords/sync', to: 'invalid_keywords#sync'
    get '/reports/home', to: 'reports#home'
    post '/reports/home', to: 'reports#home'
    get '/reports/provider', to: 'reports#provider'
    post '/reports/provider', to: 'reports#provider'
    get '/reports/search', to: 'reports#search'
    get '/reports/selection', to: 'reports#selection'
    post '/reports/selection', to: 'reports#selection'
    get '/reports/review', to: 'reports#review'
    post '/reports/review', to: 'reports#review'

    # https://stackoverflow.com/questions/21654826/how-to-rescue-page-not-found-404-in-rails
    # The “a” is actually a parameter in the Rails 3 Route Globbing technique. For example,
    # if your url was /this-url-does-not-exist, then params[:a] equals “/this-url-does-not-exist”.
    match '*a', :to => 'errors#routing', via: :get
  end
end

app/views/shared/_digital_analytics_program.html.erb
<!-- NASA Digital Analytics Program -->
<script async type="text/javascript" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=NASA&subagency=GSFC" id="_fed_an_ua_tag"></script>
<!-- End NASA Digital Analytics Program -->

app/views/shared/_footer.html.erb
<footer role="contentinfo">
  <ul class="footer-links">
    <li><span class="version badge eui-badge--md">v <%= Rails.configuration.version %>|pyQuARC <%= pyquarc_version() %></span></li>
    <li>NASA Official: Stephen Berrick</li>
    <li><a href="http://www.nasa.gov/FOIA/index.html">FOIA</a></li>
    <li><a href="http://www.nasa.gov/about/highlights/HP_Privacy.html">NASA Privacy Policy</a></li>
    <li><a href="http://www.usa.gov/">USA.gov</a></li>
  </ul>
</footer>

<!-- Scripts that should be loaded in the footer to allow for faster page loads -->
<% unless Rails.env.test? %>
  <script id="feedback-tag" src="https://fbm.earthdata.nasa.gov/for/MMT/feedback.js"></script>
  <script type="text/javascript">
    (function() {
      var initFeedback = function() {
        window.feedback.init({showIcon: false});
      }
      if (window.feedback) {
        initFeedback();
      }
      else {
        document.getElementById('feedback-tag').onload = initFeedback;
      }
    })();
  </script>
<% end %>

app/views/shared/_google_tag_manager_body.html.erb
<% if Rails.configuration.respond_to?(:tag_manager_id) %>

  <!-- Google Tag Manager (noscript) -->
  <noscript> <iframe src="https://www.googletagmanager.com/ns.html?id=<%= Rails.configuration.tag_manager_id %>"
  height="0" width="0" style="display:none;visibility:hidden"></iframe> </noscript>
  <!-- End Google Tag Manager (noscript) -->

<% end %>

app/views/shared/_google_tag_manager_head.html.erb
<% if Rails.configuration.respond_to?(:tag_manager_id) %>
  <!-- Google Tag Manager -->
  <script nonce='{SERVER-GENERATED-NONCE}'>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;var n=d.querySelector('[nonce]');
    n&&j.setAttribute('nonce',n.nonce||n.getAttribute('nonce'));f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-WNP7MLF');</script>
  <!-- End Google Tag Manager -->
<% end %>

app/views/shared/_navigation.html.erb
<div class="page_header">
  <div class="header_title">
    <h3><%= title %> <%= get_environment_display_name %></h3>
    <% if current_user.admin? %>
      <p>CMR Last Update: <%= RecordsUpdateLock.formatted_last_update %></p>
    <% end %>
  </div>

  <div class="header_menu">
  <section id="user-info">
      <div class="prof-link-container">
          <div><strong><%= current_user.name %></strong>
            <span class="eui-badge--sm daac"><%= current_user.role %></span>
          </div>
      </div>
  </section>
    <nav class="eui-menu menu_override">
      <ul>
        <li>
          <%= link_to home_path, class: "menu_link header_button" do %>
            <i class="eui-icon eui-fa-globe"></i>
            <p>Curation Home</p>
          <% end %>
        </li>
        <li>
          <%= link_to finished_records_path, class: "menu_link header_button" do %>
            <i class="fa fa-times-circle"></i>
            <p>Closed Records</p>
          <% end %>
        </li>
        <li>
          <%= link_to reports_home_path, class: "menu_link header_button" do %>
            <i class="fa fa-bar-chart"></i>
            <p>Reports</p>
          <% end %>
          <ul class="eui-sub-menu">
            <li><%= link_to "Overall Report", reports_home_path %></li>
            <li><%= link_to "Reports By DAAC", reports_provider_path %></li>
            <li><%= link_to "Reports By Selection", reports_search_path %></li>
            <li><%= link_to "Download CSV of Invalid Keywords", invalid_keywords_csv_report_path(format: :csv, provider: current_user.daac_curator? ? current_user.daac : nil
            ), data: {turbolinks: false} %>
          </ul>
        </li>

        <% if current_user.admin? || (Rails.configuration.email_preference_feature_toggle && current_user.daac_curator?) %>
          <li>
            <%= link_to "#", class: "menu_link header_button account_options" do %>
              <i class="fa fa-sliders"></i>
              <p>Account Options</p>
            <% end %>
              <ul class="eui-sub-menu">
                <% if current_user.admin? %>
                  <li id="record_refresh"><%= link_to "Refresh Records", record_refresh_path %></li>
                <% end %>
                <% if current_user.daac_curator? %>
                  <li id="email_preferences"><%= link_to "E-mail Preferences", email_preferences_path %></li>
                <% end %>
              </ul>
          </li>
        <% end %>

        <li>
        <%= link_to "https://wiki.earthdata.nasa.gov/pages/viewpage.action?spaceKey=CMR&title=CMR+Metadata+Curation+Dashboard+User+Documentation", class: "menu_link header_button", target: "_blank" do %>
          <i class="fa fa-question-circle"></i>
          <p>User&apos;s Guide</p>
        <% end %>
        </li>

        <li>
          <%= link_to destroy_user_session_path, method: :get, class: "menu_link header_button" do %>
            <i class="eui-icon eui-fa-external-link-square"></i>
            <p>Logout</p>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</div>

<div class="header_image">

</div>

<%= render(partial: 'shared/notice_message') %>

app/views/shared/_notice_message.html.erb
<noscript>
  <div id='javascript_warning' class="eui-banner--danger">
    <p class="eui-banner__message">
      <strong> JavaScript is disabled! </strong> JavaScript must be enabled for some features to work.
    </p>
  </div>
</noscript>

<% if notice %>
  <div id="notice_banner" class="eui-banner--info">
    <p class="eui-banner__message">
      <%= notice %>
      <a href="javascript:void(0)" class="eui-banner__dismiss" onclick='dismiss_banner("notice_banner")' title="Dismiss banner"><i class="eui-icon eui-fa-times-circle"></i></a>
    </p>
  </div>
<% end %>

<% if alert && alert != "" %>
  <div id="alert_banner" class="eui-banner--danger">
    <p class="eui-banner__message">
      <%= alert %>
      <a href="javascript:void(0)" class="eui-banner__dismiss" onclick='dismiss_banner("alert_banner")' title="Dismiss banner"><i class="eui-icon eui-fa-times-circle"></i></a>
    </p>
  </div>
<% end %>

<script type="text/javascript">
  function dismiss_banner(element_name) {
    document.getElementById(element_name).style.display = "none";
  }
</script>

app/views/shared/_record_buttons.html.erb
<% report ||= false %>
<% complete ||= false %>
<% complete_title ||= '' %>
<% form_id ||= '' %>

<div class="navigate-buttons">
  <%= hidden_field_tag :finished, "#{form_id == 'finished'}" %>
  <%= submit_tag("See Review Detail", class: "selectButton", disabled: true) %>

  <% if complete %>
    <%= submit_tag(complete_title || "Close", class: "completeButton", formaction: batch_complete_records_path, disabled: true, data: { confirm: "Complete and transition the selected Record(s)?" }) %>
  <% end %>

  <% if current_user.admin? || current_user.role == 'mdq_curator' %>
    <%= submit_tag("Delete Record", class: "deleteButton", formaction: hide_records_path, disabled: true, data: { confirm: "Delete this Record from the System?"}) %>

    <%= hidden_field_tag("unhide_state", form_id) %>
    <% if @unhide_record_ids.present? && @unhide_record_ids.key?(form_id) %>
      <%= hidden_field_tag("unhide_form_record_ids", @unhide_record_ids[form_id]) %>
      <%= submit_tag("Undelete", class: "undeleteButton", formaction: unhide_records_path, disabled: false, data: { confirm: "Undelete last action?"}) %>
    <% end %>

    <% if complete_title == 'Close' and current_user.admin? %>
      <%= submit_tag("Revert", class: "revertButton", formaction: revert_records_path, disabled: true, data: {confirm: "Revert this record?"}) %>
    <% end %>
<% end %>

  <% if report %>
    <%= submit_tag("Get Review Report", class: "reportButton", formaction: reports_review_path, disabled: true) %>
  <% end %>

  <%= yield %>
</div>

app/views/shared/_record_filters.html.erb
<% path_for_form ||= home_path %>
<script type="text/javascript">
  function onChangeColorFilter() {
    selectedValue = document.getElementById('color_code').value;
    if (selectedValue != 'None') {
      document.getElementById('color_code_filter_collection').checked = true;
    }
  }
</script>
<div class="record_filters searchbox_area">
  <p><strong>Filter Records:</strong></p>
  <%= form_with( url: path_for_form, method: "get", local: true) do %>
    <div class="record_filters__filters">
      <% if can?(:access, :filter_daac) %>
        <div class="record_filters__select">
          <%= label_tag(:daac, "DAAC") %>
          <%= select_tag(:daac, options_for_select(provider_select_list, selected: params[:daac])) %>
        </div>
      <% end %>

      <div class="record_filters__select">
        <span style="font-weight: bold">Campaign/Project</span>
        <%= select_tag(:campaign, options_for_select(campaign_select_list(form: path_for_form), selected: params[:campaign]), style: "width:190px") %>
      </div>
      <% if Rails.configuration.filter_by_color_feature_toggle %>
        <div class="record_filters__select">
          <span>
            <span style="font-weight: bold">Color</span>
            <span class="bubbletooltip">
              <i class="eui-icon eui-fa-info-circle"></i>
              <span class="bubbletooltiptext">Filters records containing one or more metadata elements flagged by the selected color.</span>
            </span>
          </span>
          <%= select_tag(:color_code, options_for_select([['', 'None'], ['Red (Error)', 'red'], ['Yellow (Warning)', 'yellow'], ['Blue (Information)', 'blue'], ['Any (Red/Yellow/Blue)', 'any']], selected: params[:color_code]), onchange: 'onChangeColorFilter()') %>
          <div style="display: flex; gap: 5px; align-items: center">
            <div style="display: flex; align-items: flex-end">
              <div><%= check_box_tag(:color_code_filter_collection, nil, params[:color_code_filter_collection]) %></div>
              <div style="margin-left: -2px"><%= label_tag(:color_code_filter_collection, "Collection") %></div>
            </div>
            <div style="display: flex; align-items: flex-end">
              <div><%= check_box_tag(:color_code_filter_granule, nil, params[:color_code_filter_granule]) %></div>
              <div style="margin-left: -2px"><%= label_tag(:color_code_filter_granule, "Granule") %></div>
            </div>
          </div>
        </div>
      <% end %>
      <div class="record_filters__select">
        <label for="freetext">Freetext</label>
        <input type="search" name="freetext" id="freetext" class="freetext" style="width: 200px;" value="<%=params[:freetext]%>"/>
      </div>


      <%= submit_tag("Filter", class: "selectButton") %>

    </div>

  <% end %>

</div>

app/views/shared/_records_table.html.erb
<% closed ||= false %>
<% reviews ||= false %>
<% section ||= "open" %>

<div class="table-backdrop">
  <div class="results-title">
    <p><strong><%= title %>:</strong>
      <% if title == "In DAAC Review" && @invalid_keywords.length > 0 %>
        <span class="invalid_keywords_tooltip">
          <img class="invalid_keywords_alert_icon" src="<%= asset_path('warning-icon.png') %>"  />
          <span class="invalid_keywords_tooltiptext">There are <%= @invalid_keywords.length %> invalid keywords found across <%= get_concepts(@invalid_keywords).length %> collection records.   See the Reports Menu to download a CSV of issues found.</span>
        </span>
      <% end %>
    </p>
  </div>

  <!-- Todo: Verify AuthenticityToken issue is fixed in RAILS 6.0 -->
  <!-- See CMRARC-484 and https://github.com/rails/rails/issues/24257-->
  <!-- During the RAILS 5.2 upgrade, there was an issue with the CSRF authenticity tokens.   Namely, this specific-->
  <!-- workflow:  if a user clicks See Review Details, then clicks Curation Home, then clicks Revert Record,-->
  <!-- they will get a Invalid Authenticity Token.   Workaround is to tell form_with it should not auto include the-->
  <!-- token, rather we should explicitly include it ourselves. -->
  <%= form_with( url: collection_path(id: 1), method: :put, local: true,  id: form_id, authenticity_token: false) do %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

    <div class="results-table-container">
      <div class="table-scroll">
        <%= react_component("view/PaginationTableView", { section: section, formId: form_id, current_user: current_user.id, admin: current_user.admin?, role: current_user.role }) %>
      </div>
      <%= content_for :form_buttons %>
    </div>
  <% end %>
</div>