config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope format: false do
    get '/elb_status', to: 'site#elb_status'

    devise_for :users, :controllers => {
      :omniauth_callbacks => "login"
    }

    get '/login', to: 'login#urs'

    # https://github.com/plataformatec/devise/issues/1390
    devise_scope :user do
      root to: "devise/sessions#new"
      get '/session/new' => 'devise/sessions#new', as: :new_user_session
      get '/session/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
    end

    get '/home', to: 'site#home'
    get '/general_home', to: 'site#general_home'

    resources :collections do
      collection do
        put 'refresh'
      end
    end

    get '/collections_search', to: 'collections#search'

    get 'user/email_preferences' => 'user#email_preferences', as: 'email_preferences'
    post 'user/email_preferences/update' => 'user#update_email_preferences', as: 'update_email_preferences'

    resources :granules do
      member do
        delete "replace"
        post "pull_latest"
        post "ingest_specific"
      end
    end
    resources :comments
    resources :discussions
    resources :reviews do
      member do
        put "update_review_comment"
        put "update_report_comment"
      end
    end
    resources :records do
      member do
        get "copy_prior_recommendations"
        post "complete"
        post "associate_granule_to_collection"
      end

      collection do
        get "find_records_json"
        get "finished"
        get "navigate"
        put "allow_updates"
        put "stop_updates"
        post "revert"
        post "batch_complete"
        delete "hide"
        put "unhide"
      end
    end

    get '/record_refresh', to: 'records#refresh'
    get '/invalid_keywords/csv_report', to: 'invalid_keywords#csv_report'
    get '/invalid_keywords/sync', to: 'invalid_keywords#sync'
    get '/reports/home', to: 'reports#home'
    post '/reports/home', to: 'reports#home'
    get '/reports/provider', to: 'reports#provider'
    post '/reports/provider', to: 'reports#provider'
    get '/reports/search', to: 'reports#search'
    get '/reports/selection', to: 'reports#selection'
    post '/reports/selection', to: 'reports#selection'
    get '/reports/review', to: 'reports#review'
    post '/reports/review', to: 'reports#review'

    # https://stackoverflow.com/questions/21654826/how-to-rescue-page-not-found-404-in-rails
    # The “a” is actually a parameter in the Rails 3 Route Globbing technique. For example,
    # if your url was /this-url-does-not-exist, then params[:a] equals “/this-url-does-not-exist”.
    match '*a', :to => 'errors#routing', via: :get
  end
end

app/helpers/record_helper.rb
module  RecordHelper


  # If the specified string contains a quote (") will remove it from the string
  def remove_quotes_from_value(v)
    if v.instance_of? String
      v.delete('"')
    else
      v
    end
  end

  # This is based on rails 6, deep_transform_values!
  # This will remove quotes(") from values in the hash, as when converting to json, the value's can't have quotes in them.
  def remove_quotes_from_all_values!(object)
    case object
    when Hash
      object.transform_values! { |value| remove_quotes_from_all_values!(value) }
    when Array
      object.map! { |e| remove_quotes_from_all_values!(e) }
    else
      remove_quotes_from_value(object)
    end
  end

  def daac_from_concept_id(concept_id)
    index = concept_id.rindex('-')
    return concept_id[(index+1)..-1] unless index.nil?
    raise 'Error parsing daac from concept_id'
  end

  def is_number?(object)
    true if Float(object) rescue false
  end

  # checks if the granule can be associated
  # note if the checks fail, the caller should not associate the granule record to the collection.
  def can_associate_granule?(granule_record, collection_state)
    return [true, nil] if %w(open in_arc_review).include?(collection_state)

    success = true
    messages = []
    if %w(closed).include?(collection_state)
      messages << "Can't associate collection to granule. Only open and in review collection records can be associated."
      success = false
      return [success, messages]
    end
    unless granule_record.color_coding_complete?
      messages << 'Not all columns in the associated granule have been flagged with a color!'
      success = false
    end
    unless granule_record.has_enough_reviews?
      messages << 'The associated granule needs two completed reviews.'
      success = false
    end
    if %w(in_daac_review).include?(collection_state) && !granule_record.no_second_opinions?
      messages << 'Some columns in the associated granule still need a second opinion review.  Please clear all second opinion flags'
      success = false
    end
    [success, messages]
  end

  # checks if the associated granule can be marked complete
  # note: marking a record complete checks to see if it can move to the next state.
  def can_mark_associated_granule_complete?(granule_record, collection_state)
    # it is ok to associate granule records without checks if in open or in_arc_review
    success = true
    messages = []
    unless granule_record.color_coding_complete?
      messages << 'Not all columns in the associated granule have been flagged with a color!'
      success = false
    end
    unless granule_record.has_enough_reviews?
      messages << 'The associated granule needs two completed reviews.'
      success = false
    end
    if %w(ready_for_daac_review in_daac_review).include?(collection_state) && !granule_record.no_second_opinions?
      messages << 'Some columns in the associated granule still need a second opinion review.  Please clear all second opinion flags'
      success = false
    end
    [success, messages]
  end

  def empty_contents(value)
    new_value = nil

    if value.is_a?(String)
      new_value = ""
    elsif value.is_a?(Array)
      cleared_list = value.map{ |x| empty_contents(x) }
      cleared_list = cleared_list.select { |item| item != "" }
      cleared_list = "" if cleared_list.empty?
      new_value = cleared_list
    elsif value.is_a?(Hash)
      new_value = {}
      value.each do |key, sub_value|
        new_value[key] = empty_contents(sub_value)
      end
    end

    new_value
  end

  def script_test(value)
    if value.nil? || value == ""
      return false
    end

    !(value.start_with?("OK", "ok", "Ok"))
  end

  def completed_reviews(reviews)
    reviews.reduce(0) { |sum, review| sum + review.review_state.to_i }
  end

  def reviewer_ok?(record)
    can?(:review_state, record.state.to_sym)
  end

  def complete_button_text(record)
    if record.ready_for_daac_review?
      "RELEASE TO DAAC"
    elsif record.in_daac_review?
      "CMR UPDATED"
    else
      "MARK AS DONE"
    end
  end

  def disable_complete_button?(reviews, record)
    completed_reviews(reviews) <= 1 || record.closed? || !reviewer_ok?(record)
  end

  def script_class(field)
    field[:script] && current_user.arc? ? "script" : "no_script"
  end

  def script_text_class(field)
    field[:script] && current_user.arc? ? "script_text" : "no_script_text"
  end

  def record_in_progress?(record)
    [Record::STATE_OPEN.to_s,
     Record::STATE_IN_ARC_REVIEW.to_s,
     Record::STATE_READY_FOR_DAAC_REVIEW.to_s].include?(record.state)
  end

  def copy_recommendations_active_class(record)
    record.copy_recommendations_note.nil? ? 'eui-btn--green confirm-modal-button' : 'eui-btn--disabled'
  end

  # When a record has multiples, Dashboard stores them in the value field
  # formatted like: "• <value1>\n• <value2>\n ..."
  # Returns an array like: [value1, value2, ...]
  def clean_up_campaign(campaign)
    return [] if campaign.nil?

    campaign.tr('•', '').split("\n").each(&:strip!)
  end

  def get_concepts(invalid_keywords)
    concept_ids = []
    invalid_keywords.each do |keyword|
      concept_id = keyword.concept_id
      concept_ids << concept_id unless concept_ids.include? concept_id
    end
    concept_ids
  end
end

app/views/records/_collection_section_details.html.erb
<article class="section_display flex_item">
  <button class="section_button" onclick="location.href='<%= review_path(id: params["id"], section_index: index_count) %>';">
  <%= space_digits(section[0]) %>
  <!-- arrow to review section -->
  <div class="eui-icon eui-fa-arrow-circle-right"></div>
  </button>
  <!-- dynamically add bubble divs -->
  <div id="record_bubbles" class="record_bubbles">
    <% section[1].each do |field| %>
      <% if current_field = bubble_data[field] %>
        <div id="single_bubble_container_<%= field %>" class="single_bubble_container">
          <button onclick="redirectToSection('<%= review_path(id: params["id"], section_index: index_count) %>', '<%= field %>')" class="bubble flag_<%= current_field[:color] %> <%= script_class(current_field) %> bubbletooltip">
              <p class="bubbletooltiptext"><%= split_on_capitals(field) %></p>
            <% if current_user.arc? && current_field[:opinion] && current_field[:opinion] != "" %>
              <div class="<%= script_text_class(current_field) %> bubble_opinion">2</div>
            <% elsif current_field[:feedback] %>
              <div class="<%= script_text_class(current_field) %> bubble_opinion">F</div>
            <% else %>
              <div style="visibility: hidden;" class="<%= script_text_class(current_field) %> bubble_opinion">2</div>
            <% end %>
          </button>
        </div>
      <% else %>
        <%# E is presented in the circle for error. retreiving bubble data.%>
        <div class="bubble flag_white no_script" title="field">
            <div class="<%= script_text_class(current_field) %> bubble_opinion">E</div>
        </div>

      <% end %>
    <% end %>

    <script>
      function redirectToSection(path, field) {
        sessionStorage.setItem('targetField', field)
        location.href = path
      }
    </script>
  </div>
</article>

app/views/records/_navigation_section_details.html.erb
<article class="section_display flex_item">
  <button class="section_button" onclick="location.href='<%= review_path(id: params["id"], section_index: 0) %>';">
  <%= title %>
  <!-- arrow to review section -->
  <div class="eui-icon eui-fa-arrow-circle-right"></div>
  </button>
  <!-- dynamically add bubble divs -->
  <div class="nav_bubbles">
    <% bubble_data.each_with_index do | bubble, index | %>
      <% script_class = bubble[:script] ? "script" : "no_script" %>

      <div class="bubble flag_<%= bubble[:color] %> <%= script_class %>" title="<%= bubble[:field_name] %>">
      </div>
    <% end %>
  </div>
</article>  

app/views/records/finished.html.erb
<%= render(partial: 'shared/navigation', locals: {title: "METADATA CURATION: HOME"}) %>

<div class="curation_box">
  <div class="space_box"></div>

  <div class="results-area">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <% if current_user.daac_curator? %>
      <% content_for :form_buttons do %>
        <%= render partial: "shared/record_buttons", locals: {form_id: "finished", report: true} %>
      <% end %>
      <%= render partial: "shared/record_filters", locals: { path_for_form: finished_records_path } %>
      <%= render partial: "shared/records_table", locals: {form_id: "finished", section: "closed_finished", title: "DAAC Completed Records"} %>
    <% else %>
      <%= render partial: "shared/record_filters", locals: { path_for_form: finished_records_path } %>

      <% if can?(:review_state, Record::STATE_CLOSED) %>
        <% content_for :form_buttons do %>

          <%= render layout: "shared/record_buttons", locals: { form_id: "finished", report: true } do %>


            <% if current_user.admin? %>
              <%= submit_tag("Exclude Record from Updates", class: "finishedButton", formaction: stop_updates_records_path, disabled: true, data: {confirm: "Exclude this Record from Future CMR Updates?"}) %>
              <%= submit_tag("Refresh", class: "refreshButton", formaction: refresh_collections_path, disabled: true) %>
              <%= submit_tag("Reopen", class: "revertButton", formaction: revert_records_path, disabled: true, data: { confirm: "Reopen this record?"}) %>
            <% end %>

          <% end %>
        <% end %>

        <%= render partial: "shared/records_table", locals: {form_id: "closed", section: "closed", closed: true, report: true, title: "Team's Closed Records" } %>
      <% end %>

      <% if can?(:review_state, Record::STATE_FINISHED) %>

        <% content_for :form_buttons, flush: true do %>

          <%= render(layout: "shared/record_buttons", locals: { form_id: "finished", report: true}) do %>

            <% if current_user.admin? %>
              <%= submit_tag("Allow CMR Updates", class: "cmrUpdateButton", formaction: allow_updates_records_path, disabled: true) %>
            <% end %>
          <% end %>

        <% end %>

        <%= render partial: "shared/records_table", locals: {form_id: "finished", section: "finished", title: "Finished Records" } %>

      <% end %>
    <% end %>
  </div>
</div>

app/views/records/show.html.erb
<%= render(partial: 'shared/navigation', locals: {title: "METADATA CURATION: RECORD"}) %>
<%= render(partial: 'reviews/navbar', locals: {page: "navigation", record: @record, user_email: current_user.email }) %>

<!-- everything below the nav -->
<section class="record_review_data">
  <div class="outer_flexbox">


    <!-- container of metadata sections -->
    <div class="section_container outer_flex_item_left">
      <!-- header for sections -->

      <div class="section_header">
        <% if can?(:copy_recommendations, @record) %>
          <div class="review_buttons_row">
            <% modal_id = "copy_prior_recommendations-modal-id-#{@record.id}" %>
            <input class="<%=copy_recommendations_active_class(@record)%>" type="button" id="copy_prior_recommendations_button" name="<%= modal_id %>" href="#<%= modal_id %>" value="Copy Prior Recommendations"/>
            <div id="<%= modal_id %>" class="eui-modal-content confirm-modal">
              <a href="#" class="modal-close float-r"><i class="fa fa-times"></i><span class="is-invisible">Close</span></a>
              <form method="get" action="<%=copy_prior_recommendations_record_path(@record.id)%>">
                <br>
                Concept ID: <input type="text" id="concept_id" name="concept_id" value="<%= @prior_record_revision_id == '' ? '' : @record.concept_id %>"/><br>
                Revision ID: <input type="text" id="revision_id" name="revision_id" value="<%= @prior_record_revision_id %>"/>
                <p>
                <input class="smallSelectButton eui-btn--green" type="submit" value="Copy Recommendations">
                  <a href="#"><input type="button" class="smallSelectButton confirm-no-button" value="Cancel"/></a>
                </p>
              </form>
            </div>
          </div>
        <% end %>
        <h3>METADATA ELEMENTS</h3>
      </div>


      <!-- two coulmns holder -->
      <div class="flex_container">
        <!-- left column of section details -->
        <div class="flex_column">
        <% @record_sections.each_with_index do |section, index_count| %>
          <% if index_count.to_i % 3 == 0 %>
          <%= render(partial: 'collection_section_details', locals: {section: section, index_count: index_count, bubble_data: @bubble_data}) %>
          <% end %>
        <% end %>


        </div>

        <!-- right column of section details -->
        <div class="flex_column">
          <% @record_sections.each_with_index do |section, index_count| %>
            <% if index_count.to_i % 3 == 1 %>
            <%= render(partial: 'collection_section_details', locals: {section: section, index_count: index_count, bubble_data: @bubble_data}) %>
            <% end %>
          <% end %>
        </div>


        <!-- right column of section details -->
        <div class="flex_column">
          <% @record_sections.each_with_index do |section, index_count| %>
            <% if index_count.to_i % 3 == 2 %>
            <%= render(partial: 'collection_section_details', locals: {section: section, index_count: index_count, bubble_data: @bubble_data}) %>
            <% end %>
          <% end %>
        </div>
      </div>

    </div>

    <!-- right side completion/reviewers metrics -->
    <div class="outer_flex_item_right">
      <div class="review_comments">
        <!-- header for sections -->
        <div class="section_header">
          <h3>Review Comments</h3>
        </div>

        <% if !@user_review.completed? && !@marked_done %>
          <br>

          <%= form_for @user_review, html: {id: :review_form} do |f| %>
            <%= f.hidden_field :record_id, { :value => @user_review.record_id } %>
            <%= f.hidden_field :id, { :value => @user_review.id } %>
            <%= f.hidden_field :user_id, { :value => @user_review.user_id } %>
            <%= f.hidden_field :review_state, { :value => 1 } %>

            <% if can?(:create_review_comments, @user_review) %>
              <p class="review_comments__headline">ARC Review Comments:</p>
              <p class="review_comments__subheadline">Visible only to ARC curators (optional)</p>
              <%= f.text_area :review_comment, html: {id: :review_comment} %>
            <% end %>

            <% if can?(:create_report_comments, @user_review) %>
              <p class="review_comments__headline">Report Review Comments:</p>
              <p class="review_comments__subheadline">Visible to all curators (required)</p>
              <%= f.text_area :report_comment, html: { id: :report_comment } %>

              <script type="text/javascript">
                document.getElementById("review_report_comment").oninput = function() {
                  document.getElementById("review_complete_button").disabled = false;
                }
              </script>
            <% end %>

          <% end %>

        <% end %>

        <% if @marked_done %>
          <p class="completed_notice">
            <strong>Review Has Been Completed and Closed</strong>
          </p>
        <% end %>

        <% @reviews.each do |review| %>
          <div class="single_comment">
            <p><strong>Reviewer: <%= review.user.email %></strong></p>
            <p><%= review.formatted_date %></p>

            <% if can?(:view_review_comments, review) %>
              <div class="comment_update">
                <!--Column 1: the text-->

                <% unless review.review_comment.blank? %>
                  <div class="comment_text_label" id=<%="text" + getFormReviewId(review)%>><%= string_html_format(review.review_comment) %></div>
                <% else %>
                  <div id=<%="text" + getFormReviewId(review)%> class="no_comments_label">No Comment</div>
                <% end %>

                <% if can?(:create_review_comments, @user_review) && review.user.id == current_user.id %>
                  <% unless review.review_comment.nil?%>
                    <!--Column 2: the form for update-->
                    <div id=<%=getFormReviewId(review)%> class="comment_review_update_form" style="display: none;">
                      <%= form_with( url: update_review_comment_review_path(id: review.id) , method: "put", id: review.id, local: true, authenticity_token: false) do %>
                        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                        <textarea rows="4" name="review_comment" id="review_id" style="background-color: #e7e7e7"><%= review.review_comment%></textarea>
                        <input type="submit" class="smallSelectButton confirm-no-button" value="UPDATE"/>
                        <a href="#"><input type="button" class="smallSelectButton confirm-no-button comment_cancel_button" value="Cancel"/></a>
                    <% end %>
                    </div>
                    <!--Column 3: the update icon-->
                    <div id=<%="icon-group" + getFormReviewId(review)%> class="comment_review_update_icons">
                      <i class="fa fa-edit fa-lg" style="font-size:16px" aria-hidden="true" onclick='toggle("<%=getFormReviewId(review)%>");toggle("<%="text" + getFormReviewId(review)%>"); toggle("<%="icon-group" + getFormReviewId(review)%>")'></i>
                    </div>
                  <% end %>
                <% end %>
                </div>
            <% end %>

            <% if can?(:view_report_comments, review) %>
              <div class="comment_update">
                <!--Column 1: the text-->

                <% unless review.report_comment.blank? %>
                  <div class="comment_text_label" id=<%="text" + getFormReportId(review)%>><%= string_html_format(review.report_comment) %></div>
                <% else %>
                  <div id=<%="text" + getFormReportId(review)%> class="no_comments_label">No Comment</div>
                <% end %>

                <% if can?(:create_report_comments, @user_review) && review.user.id == current_user.id %>
                  <% unless review.report_comment.nil?%>
                    <!--Column 2: the form-->
                    <div id=<%=getFormReportId(review)%> class="comment_report_update_form" style="display: none;">
                      <%= form_with( url: update_report_comment_review_path(id: review.id) , method: "put", id: review.id, local: true, authenticity_token: false) do %>
                        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                        <textarea rows="4" name="report_comment" id="report_id" style="background-color: #e7e7e7"><%= review.report_comment%></textarea>
                        <input type="submit" class="smallSelectButton confirm-no-button" value="UPDATE"/>
                        <a href="#"><input type="button" class="smallSelectButton confirm-no-button comment_cancel_button" value="Cancel"/></a>
                    <% end %>
                    </div>
                    <!--Column 3: the update icon-->
                    <div id=<%="icon-group" + getFormReportId(review)%> class="comment_report_update_icons">
                      <i class="fa fa-edit fa-lg" style="font-size:16px" aria-hidden="true" onclick='toggle("<%=getFormReportId(review)%>");toggle("<%="text" + getFormReportId(review)%>"); toggle("<%="icon-group" + getFormReportId(review)%>")'></i>
                    </div>
                  <% end %>
                <% end %>
                </div>
            <% end %>
          </div>
        <% end %>

      </div>
    </div>

  </div>


  <%= render(partial: 'reviews/legend') %>

</section>

<script type="text/javascript" charset="utf-8">
  function toggle(messageId) {
    var x = document.getElementById(messageId);
    if (x.style.display === "none") {
      x.style.display = "block";
    } else {
      x.style.display = "none";
    }
  }
</script>