config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope format: false do
    get '/elb_status', to: 'site#elb_status'

    devise_for :users, :controllers => {
      :omniauth_callbacks => "login"
    }

    get '/login', to: 'login#urs'

    # https://github.com/plataformatec/devise/issues/1390
    devise_scope :user do
      root to: "devise/sessions#new"
      get '/session/new' => 'devise/sessions#new', as: :new_user_session
      get '/session/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
    end

    get '/home', to: 'site#home'
    get '/general_home', to: 'site#general_home'

    resources :collections do
      collection do
        put 'refresh'
      end
    end

    get '/collections_search', to: 'collections#search'

    get 'user/email_preferences' => 'user#email_preferences', as: 'email_preferences'
    post 'user/email_preferences/update' => 'user#update_email_preferences', as: 'update_email_preferences'

    resources :granules do
      member do
        delete "replace"
        post "pull_latest"
        post "ingest_specific"
      end
    end
    resources :comments
    resources :discussions
    resources :reviews do
      member do
        put "update_review_comment"
        put "update_report_comment"
      end
    end
    resources :records do
      member do
        get "copy_prior_recommendations"
        post "complete"
        post "associate_granule_to_collection"
      end

      collection do
        get "find_records_json"
        get "finished"
        get "navigate"
        put "allow_updates"
        put "stop_updates"
        post "revert"
        post "batch_complete"
        delete "hide"
        put "unhide"
      end
    end

    get '/record_refresh', to: 'records#refresh'
    get '/invalid_keywords/csv_report', to: 'invalid_keywords#csv_report'
    get '/invalid_keywords/sync', to: 'invalid_keywords#sync'
    get '/reports/home', to: 'reports#home'
    post '/reports/home', to: 'reports#home'
    get '/reports/provider', to: 'reports#provider'
    post '/reports/provider', to: 'reports#provider'
    get '/reports/search', to: 'reports#search'
    get '/reports/selection', to: 'reports#selection'
    post '/reports/selection', to: 'reports#selection'
    get '/reports/review', to: 'reports#review'
    post '/reports/review', to: 'reports#review'

    # https://stackoverflow.com/questions/21654826/how-to-rescue-page-not-found-404-in-rails
    # The “a” is actually a parameter in the Rails 3 Route Globbing technique. For example,
    # if your url was /this-url-does-not-exist, then params[:a] equals “/this-url-does-not-exist”.
    match '*a', :to => 'errors#routing', via: :get
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include ReportsHelper

  before_action :authenticate_user!

  def home
    @metric_data         = MetricData.new(Collection.all_metadata(application_mode))
    @granule_metric_data = MetricData.new(Granule.all_metadata(application_mode))

    respond_to do |format|
      format.html
      format.csv { send_data(render_to_string, filename: "cmr_dashboard_metrics.csv") }
    end
  end

  def provider
    if params[:daac] && params[:daac] != "Select DAAC"
      @metric_data         = MetricData.new(Collection.by_daac(params[:daac]))
      @granule_metric_data = MetricData.new(Granule.by_daac(params[:daac]))
    end

    respond_to do |format|
      format.html
      format.csv { send_data(render_to_string, filename: "#{params[:daac]}_metrics.csv") }
    end
  end

  def search
    begin
      @search_iterator, @collection_count = Cmr.contained_collection_search(params[:free_text], params[:provider], params[:curr_page], 2000, application_mode)
    rescue Cmr::CmrError, Net::OpenTimeout, Net::ReadTimeout
      flash[:alert] = 'There was an error connecting to the CMR System, please try again'
      redirect_to reports_search_path
    rescue
      flash[:alert] = 'There was an error searching the system'
      redirect_to reports_search_path
    end
  end

  def selection
    concept_ids = params[:records].split(",")

    @collections = Collection.all_metadata(application_mode).where(concept_id: concept_ids)
    @granules    = @collections.map(&:granules).flatten

    @metric_data         = MetricData.new(@collections)
    @granule_metric_data = MetricData.new(@granules)

    respond_to do |format|
      format.html
      format.csv { send_data(render_to_string, filename: "cmr_selection_metrics.csv") }
    end
  end

  def review
    full_report = params[:full_report] === "true"
    @records = Record.where(id: params[:record_id])
    @granule_associations = {}
    @records.each do |record|
      value = record.associated_granule_value
      if value.nil? || value.empty? || value == 'Undefined'
        @granule_associations[record.id] = 'Undefined'
      elsif value == 'No Granule Review'
        @granule_associations[record.id] = value
      else
        granule_record = Record.where(id: value).first
        @granule_associations[record.id] = granule_record
      end
    end

    respond_to do |format|
      format.html
      format.csv { send_data(MultiRecordCsv.new(@records).to_csv(full_report), filename: "metrics_report_#{DateTime.now.to_i}.csv", type: "application/csv", disposition: 'attachment') }
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  include ApplicationHelper

  def records_with_reviews_by_month
    begin_date = (Date.today - 10.months).beginning_of_month
    end_date   = Date.today.end_of_month


    # Finds the records with reviews completed that month #
    records = Record.all_records(application_mode).joins(:reviews).where("reviews.review_completion_date >= :begin_date AND reviews.review_completion_date <= :end_date",
      begin_date: begin_date, end_date: end_date)

    # Counts the unique records that have a review in the month
    count = records.group("to_char(reviews.review_completion_date, 'YYYY-MM')").distinct.count

    10.downto(0).map do |month_mod|
      date = (Date.today - month_mod.months).strftime("%Y-%m")
      count[date].to_i
    end
  end

  def get_month_list
    (10).downto(0).map do |month_mod|
      date = Date.today - month_mod.months
      date.strftime("%b %y")
    end
  end

  def record_data_colors(record, color)
    record.record_datas.where(color: color)
  end

  def closed_records_count
    closed = Record.all_records(application_mode).closed
    closed = closed.daac(params[:daac]) if params[:daac]
    closed.count
  end

  def finished_records_count
    finished = Record.all_records(application_mode).finished
    finished = finished.daac(params[:daac]) if params[:daac]

    finished.count
  end

  def collection_finished_count
    @collection_finished_count ||= if params[:daac]
                                     Collection.by_daac(params[:daac]).finished.count
                                   else
                                     Collection.all_metadata(application_mode).finished.count
                                   end
  end

  def cmr_total_collection_count()
    @cmr_total_collection_count ||= Cmr.total_collection_count(params[:daac], provider_list)
  end

  def get_field_colors(record)
    MetricSet.new([record]).color_counts
  end
end

app/views/reports/_finished_chart.js.erb
<%# ChartFinished - bar chart showing finished records %>
var ctx = document.getElementById("ChartFinished");

var barOptionsStacked = {
  scales: {
    xAxes: [{
      ticks: {
        beginAtZero: true,
        fontFamily:  "sans-serif",
        fontSize:    11
      },
      scaleLabel:{
        display: false
      },
      gridLines: {
      },
      stacked: false
    }],
    yAxes: [{
      gridLines: {
        display:       false,
        color:         "#fff",
        zeroLineColor: "#fff",
        zeroLineWidth: 0
      },
      ticks: {
        fontFamily: "sans-serif",
        fontSize:   11
      },
      stacked:      false,
      barThickness: 30
    }]
  },
  legend:{
    display: true,
    position: "bottom"
  },
  maintainAspectRatio: false,
  pointLabelFontFamily : "Quadon Extra Bold",
  scaleFontFamily : "Quadon Extra Bold"
};

var data = {
  labels: [""],

  datasets: [{
    label: "Finished by DAAC",
    data: [<%= closed_records_count %>],
    backgroundColor: "rgba(58, 184, 65, 0.6)"
  },{
    label: "Marked Complete by ARC",
    data: [<%= finished_records_count %>],
    backgroundColor: "rgba(58, 184, 65, 1)"
  }]
}

var myChart = new Chart(ctx, {
  type: 'horizontalBar',
  data: data,
  options: barOptionsStacked
});

app/views/reports/_guage.html.erb
<div class="sub_section_title">
  REVIEW METRICS
</div>

<div class="score_section">

  <div>
    <%= render(partial: 'title_bar', locals: {title: "ORIGINAL AVERAGE QUALITY"}) %>
    <div class="surrounding_box score_box">
      <div class="data_area">
        <div id="<%= type %>ChartGuageOriginal"></div>
      </div>
    </div>
  </div>

  <div>
    <%= render(partial: 'title_bar', locals: {title: "UPDATED AVERAGE QUALITY"}) %>
    <div class="surrounding_box score_box">
      <div class="data_area">
          <div id="<%= type %>ChartGuageUpdated"></div>
      </div>
    </div>
  </div>

  <div>
    <%= render(partial: 'title_bar', locals: {title: "FINAL AVERAGE QUALITY"}) %>
    <div class="surrounding_box score_box">
      <div class="data_area">
          <div id="<%= type %>ChartGuageFinal"></div>
      </div>
    </div>
  </div>
</div>

<div class="print_width">

</div>

<script type="text/javascript">
  <%= render partial: 'guage_charts', formats: [:js], locals: { metric_data: metric_data, type: type } %>
</script>

app/views/reports/_ingest_chart.js.erb
<%# ChartIngest - chart showing ingest of records vs total # in cmr%>
var barOptionsStacked = {
  tooltips: {
    enabled: false
  },
  hover :{
    animationDuration:0
  },
  scales: {
      xAxes: [{
        ticks: {
          beginAtZero:true,
          fontFamily: "sans-serif",
          fontSize:11
        },
        scaleLabel:{
          display:false
        },
        gridLines: {
        },
        stacked: true
      }],
      yAxes: [{
          gridLines: {
            display:false,
            color: "#fff",
            zeroLineColor: "#fff",
            zeroLineWidth: 0
          },
          ticks: {
            fontFamily: "sans-serif",
            fontSize:11
          },
          stacked: true,
          barThickness: 50
      }]
  },
  legend:{
    display:true,
    position: "bottom"
  },
  maintainAspectRatio: false,

  animation: {
    onComplete: function () {
      var chartInstance = this.chart;
      var ctx = chartInstance.ctx;
      ctx.textAlign = "left";

      Chart.helpers.each(this.data.datasets.forEach(function (dataset, i) {
          var meta = chartInstance.controller.getDatasetMeta(i);
          Chart.helpers.each(meta.data.forEach(function (bar, index) {
            data = dataset.data[index];
            if(i==0){
              ctx.fillStyle = "#3ab841";
              ctx.font = "20px sans-serif";
              ctx.fillText(data, <%= 25 + ((collection_finished_count.to_f / cmr_total_collection_count) * 500) %>, bar._model.y-47);
            } else {
              ctx.font = "25px sans-serif";
              ctx.fillStyle = "#3e3e40";
              ctx.fillText(<%= cmr_total_collection_count %>, bar._model.x - 60, bar._model.y - 15);
            }
          }),this)
      }),this);
    }
  },
  pointLabelFontFamily : "Quadon Extra Bold",
  scaleFontFamily : "Quadon Extra Bold",
};

var ctx = document.getElementById("ChartIngest");
var myChart = new Chart(ctx, {
  type: 'horizontalBar',
  data: {
    labels: [""],

    datasets: [{
      label: "Number of Completed Reviews",
      data: [<%= collection_finished_count %>],
      backgroundColor: "#3ab841",
      hoverBackgroundColor: "#3ab841"
    },{
      label: "Total Number of Collections in CMR",
      // Subtract Number Reviewed from total, otherwise graphs would stack
      // bars on top of each other
      data: [<%= cmr_total_collection_count - collection_finished_count %>],
      backgroundColor: "#dbdcdd",
      hoverBackgroundColor: "#dbdcdd"
    }]
  },

  options: barOptionsStacked
});

app/views/reports/_ingest_section.html.erb
<div class="ingest_section">
    <%= render(partial: 'title_bar', locals: {title: "COLLECTION REVIEW PROGRESS"}) %>
    <div class="surrounding_box">
      <div class="graph_container">
        <canvas id="ChartIngest"></canvas>
      </div>
    </div>
</div>

<script type="text/javascript">
  <%= render partial: 'ingest_chart', formats: [:js] %>
</script>

app/views/reports/_review_record.erb
<div class="report_sub_title first_sub_title">
  <div class="title_box">
    <%= record.concept_id %>-<%= record.revision_id %>
  </div>
  <div class="title_text">

  </div>
</div>

<div class="stats_area">

  <section class="report_overall">

    <div class="metrics_section">
      <%= render(partial: 'title_bar', locals: {title: "RECORD METRICS"}) %>
      <div class="surrounding_box">
        <% if record.collection? %>

          <table class="metrics_header">
            <tr class="header_row">
              <td>Concept Id</td>
              <td>Revision Id</td>
              <td>Short Name</td>
              <td>DAAC</td>
              <td>Source File</td>
              <td>Format</td>
              <td>Review Close Date</td>
            </tr>
            <tr>
              <td><%= record.concept_id.partition('-').first %></td>
              <td><%= record.revision_id %></td>
              <td><%= record.short_name %></td>
              <td><%= record.daac %></td>
              <td><%= link_to "UMM", record.umm_json_link, target:"_blank" %></td>
              <td><%= record.format == 'umm_json' ? 'umm-c' : record.format %></td>
              <td><%= record.formatted_closed_date %></td>
            </tr>
          </table>

        <% else %>

          <% granule = record.recordable %>
          <table class="metrics_header">
            <tr class="header_row">
              <td>Concept Id</td>
              <td>Revision Id</td>
              <td>Short Name</td>
              <td>DAAC</td>
              <td>Collection Concept Id</td>
              <td>Source File</td>
              <td>Format</td>
              <td>Review Close Date</td>
            </tr>
            <tr>
              <td><%= record.concept_id.partition('-').first %></td>
              <td><%= record.revision_id %></td>
              <td><%= granule.collection_short_name %></td>
              <td><%= record.daac %></td>
              <td><%= granule.collection_concept_id.partition('-').first %></td>
              <td><%= link_to "Native", record.native_link %></td>
              <td><%= record.format == 'umm_json' ? 'umm-g; version='+(record.format_version || "n/a") : 'echo10'%></td>
              <td><%= record.formatted_closed_date %></td>
            </tr>
          </table>

        <% end %>

        <table>
          <tr class="header_row">
            <td>Reviewer</td>
            <td>Date of Review</td>
            <td>Review Comment</td>
          </tr>
          <% record.reviews.each do |review| %>
            <tr>
              <td><%= review.reviewer_email %></td>
              <td><%= review.formatted_date %></td>
              <td class="report_comment"><%= review.report_comment %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>

    <div class="metrics_spacing"></div>


    <% field_colors = get_field_colors(record) %>
    <div class="quality_row">
      <div class="surrounding_box quality_box">
        <%= render(partial: 'title_bottom_bar', locals: {title: "QUALITY OVERVIEW"}) %>
        <div class="data_area">
          <div class="data_text">
            <p>NUMBER OF COLLECTION</p>
            <p>ELEMENTS REVIEWED</p>
            <p class="checked_num"><%= field_colors.values.sum %></p>
          </div>
          <div class="doughnut_graph_container">
            <canvas id="ChartFlag<%= record.concept_id %>-<%= record.revision_id %>"></canvas>
          </div>
        </div>
        <div class="legend_area" id="original_quality_legend">
          <div class="legend_row">
            <div class="legend_item first_item">
              <div class="color_box green">
              </div>
              <p>ELEMENTS PASSED <br>(<%= field_colors["green"] %>)</p>
            </div>
            <div class="legend_item">
              <div class="color_box yellow">
              </div>
              <p>ELEMENTS WITH WARNINGS <br>(<%= field_colors["yellow"] %>)</p>
            </div>
          </div>
          <div class="legend_row">
            <div class="legend_item first_item">
              <div class="color_box blue">
              </div>
              <p>ELEMENTS NOTED <br>(<%= field_colors["blue"] %>)</p>
            </div>
            <div class="legend_item">
              <div class="color_box red">
              </div>
              <p>ELEMENTS FAILED <br>(<%= field_colors["red"] %>)</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


  <%# templating the 3 sections using a short 2d array %>
  <% [
       ["red_section", "RED", record_data_colors(record, "red")],
       ["yellow_section", "YELLOW", record_data_colors(record, "yellow")],
       ["blue_section", "BLUE", record_data_colors(record, "blue")]
     ].each do |section_name, color, elements| %>

    <section class="<%= section_name %>">

      <div class="single_color_table_holder">
        <div class="title_holder">
          <p class=<%= "#{section_name}_tab" %>><%= "#{color} FLAGGED ELEMENTS" %></p>
        </div>
        <div class="surrounding_box">
          <table class="flag_table">
            <tr class="header_row">
              <td>Element</td>
              <td>Value</td>
              <td>Recommendation</td>
            </tr>
            <% elements.each do |element| %>
              <tr>
                <td class="element_comment"><%= element.column_name %></td>
                <td class="report_comment"><%= element.value %></td>
                <td class="recommendation_comment"><%= element.recommendation %></td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>

    </section>
  <% end %>

  <div class="print_width">
  </div>

  <script type="text/javascript">
    <%= render partial: 'review_chart', formats: [:js], locals: { record: record, field_colors: field_colors } %>
  </script>

</div>

app/views/reports/_reviewed_elements.html.erb
<div class="quality_row">
  <div>
    <%= render(partial: 'title_bar', locals: {title: "ORIGINAL REVIEW"}) %>
    <div class="surrounding_box quality_box chart_padding">
      <div class="data_area">
        <div class="data_text">
          <p>NUMBER OF COLLECTION</p>
          <p>ELEMENTS REVIEWED</p>
          <p class="checked_num"><%= metric_data.original_color_counts.values.sum %></p>
        </div>
        <div class="doughnut_graph_container">
          <canvas id="<%= type %>ChartFlagOriginal"></canvas>
        </div>
      </div>
      <div class="legend_area" id="original_quality_legend">
        <div class="legend_row">
          <div class="legend_item first_item">
            <div class="color_box green">
            </div>
            <p>ELEMENTS PASSED <br>(<%= metric_data.original_color_counts["green"] %>)</p>
          </div>
          <div class="legend_item">
            <div class="color_box yellow">
            </div>
            <p>ELEMENTS WITH WARNINGS <br>(<%= metric_data.original_color_counts["yellow"] %>)</p>
          </div>
        </div>
        <div class="legend_row">
          <div class="legend_item first_item">
            <div class="color_box blue">
            </div>
            <p>ELEMENTS NOTED <br>(<%= metric_data.original_color_counts["blue"] %>)</p>
          </div>
          <div class="legend_item">
            <div class="color_box red">
            </div>
            <p>ELEMENTS FAILED <br>(<%= metric_data.original_color_counts["red"] %>)</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div>
    <%= render(partial: 'title_bar', locals: {title: "UPDATED REVIEW"}) %>
    <div class="surrounding_box quality_box chart_padding">
      <div class="data_area">
        <div class="data_text">
          <p>NUMBER OF COLLECTION</p>
          <p>ELEMENTS REVIEWED</p>
          <p class="checked_num"><%= metric_data.updated_color_counts.values.sum %></p>
        </div>
        <div class="doughnut_graph_container">
          <canvas id="<%= type %>ChartFlag"></canvas>
        </div>
      </div>
      <div class="legend_area" id="original_quality_legend">
        <div class="legend_row">
          <div class="legend_item first_item">
            <div class="color_box green">
            </div>
            <p>ELEMENTS PASSED <br>(<%= metric_data.updated_color_counts["green"] %>)</p>
          </div>
          <div class="legend_item">
            <div class="color_box yellow">
            </div>
            <p>ELEMENTS WITH WARNINGS <br>(<%= metric_data.updated_color_counts["yellow"] %>)</p>
          </div>
        </div>
        <div class="legend_row">
          <div class="legend_item first_item">
            <div class="color_box blue">
            </div>
            <p>ELEMENTS NOTED (<%= metric_data.updated_color_counts["blue"] %>)</p>
          </div>
          <div class="legend_item">
            <div class="color_box red">
            </div>
            <p>ELEMENTS FAILED <br>(<%= metric_data.updated_color_counts["red"] %>)</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div>
    <%= render(partial: 'title_bar', locals: {title: "FINAL REVIEW"}) %>
    <div class="surrounding_box quality_box chart_padding">
      <div class="data_area">
        <div class="data_text">
          <p>NUMBER OF COLLECTION</p>
          <p>ELEMENTS REVIEWED</p>
          <p class="checked_num"><%= metric_data.final_color_counts.values.sum %></p>
        </div>
        <div class="doughnut_graph_container">
          <canvas id="<%= type %>ChartFlagFinal"></canvas>
        </div>
      </div>
      <div class="legend_area" id="original_quality_legend">
        <div class="legend_row">
          <div class="legend_item first_item">
            <div class="color_box green">
            </div>
            <p>ELEMENTS PASSED <br>(<%= metric_data.final_color_counts["green"] %>)</p>
          </div>
          <div class="legend_item">
            <div class="color_box yellow">
            </div>
            <p>ELEMENTS WITH WARNINGS <br>(<%= metric_data.final_color_counts["yellow"] %>)</p>
          </div>
        </div>
        <div class="legend_row">
          <div class="legend_item first_item">
            <div class="color_box blue">
            </div>
            <p>ELEMENTS NOTED (<%= metric_data.final_color_counts["blue"] %>)</p>
          </div>
          <div class="legend_item">
            <div class="color_box red">
            </div>
            <p>ELEMENTS FAILED <br>(<%= metric_data.final_color_counts["red"] %>)</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  <%= render partial: 'reviewed_elements_charts', formats: [:js], locals: { metric_data: metric_data, type: type } %>
</script>

app/views/reports/_update_section.html.erb
<div class="update_section">
  <%= render(partial: 'title_bar', locals: {title: "UPDATED COLLECTIONS PROGRESS"}) %>
  <div class="surrounding_box">
    <div class="updates_graph_container">
      <canvas id="ChartUpdate"></canvas>
    </div>
  </div>
</div>

<script type="text/javascript">
  <%= render partial: 'update_chart', formats: [:js], locals: { metric_data: metric_data } %>
</script>

app/views/reports/provider.html.erb
<%= render(partial: 'shared/navigation', locals: {title: "REPORTS HOME PAGE"}) %>

<div class="reports_box">
  <div class="report_top">
    <div class="report_drop_down">
      <p>SELECT METRICS BY DAAC: </p>
      <p><%= select_tag(:provider, options_for_select(select_daac_list, selected: params[:daac])) %></p>

      <script type="text/javascript">
        var selecter = document.getElementById("provider");
        selecter.onchange = function() {
          if (!(selecter.value == '<%= ApplicationHelper::SELECT_DAAC %>')) {
            document.location = '/reports/provider?daac=' + selecter.value;
          }
        }
      </script>
    </div>
    <div class="report_buttons">
      <%= button_to reports_provider_path(format: :csv, daac: params[:daac]), data: {turbolinks: false}, class: "report_button" do %>
        <p>EXPORT METRICS</p>
        <i class="fa fa-file-excel-o"></i>
      <% end %>
      <div id="pdf_button" class="report_button">
        <p>PRINT PDF COPY</p>
        <i class="fa fa-file-pdf-o"></i>
      </div>
    </div>
  </div>

  <% if @metric_data %>

    <%= render partial: "section_title", locals: { title: "BY DAAC VIEW" } %>

    <div class="stats_area">

      <%# This div grouped to be moved up for the display when printed %>
      <section class="report_overall section_holder">
        <div class="section_title">
          ARC PROGRESS
        </div>

        <%= render "ingest_section" %>

        <br>

        <%= render partial: "update_section", locals: { metric_data: @metric_data } %>

        <%= render "finished_section" %>

        <br>

        <div class="section_break">
        </div>

      </section>
    </div>
  <% end %>
</div>

<% if @metric_data %>
  <%= render partial: "data_section", locals: { metric_data: @metric_data, type: "Collection", title: "BY DAAC VIEW" } %>

  <%= render partial: "data_section", locals: { metric_data: @granule_metric_data, type: "Granule", title: "BY DAAC VIEW" } %>
<% end %>

app/views/reports/search.html.erb
<%= render(partial: 'shared/navigation', locals: {title: "METADATA CURATION: SEARCH"}) %>


<div class="search_page_box">
  <div class="space_box"></div>

    <div class="search_title">
      <p><strong>Search the Metadata Review System:</strong></p>
    </div>

    <%= form_with( url: reports_search_path, method: "get", local: true) do %>
      <%= select_tag(:provider,options_for_select(provider_select_list, :selected => params[:provider])) %>
      <%= text_field_tag(:free_text, params[:free_text]) %>
      <%= hidden_field_tag(:curr_page, "1") %>
      <%#= submit_tag("", class: 'search_button eui-icon eui-fa-search') %>
      <button class="search_button">
        <i class="eui-icon eui-fa-search"></i>
      </button>
    <% end %>

    <br>
    <% if params[:free_text] %>
      <p><strong>Search Results:</strong></p>

      <div class="results_box">

        <div class="search_phrase">
          <p>Search Phrase = <%= params[:free_text] %></p>
        </div>
        <div class="total_results">
          <p>Total Results = <%= @collection_count %></p>
        </div>


        <div class="bottom_row">
          <div class="select_collection">
            <%= form_with( url: reports_selection_path ,  method: "get", id: 'select_form', local: true) do %>
              <%= hidden_field_tag(:records, "", id: "records_holder") %>
              <%= button_tag("Select Records", id: 'select_submit') %>
            <% end %>
          </div>
        </div>

        <% if params[:free_text] && @search_iterator.empty? %>
          <div class="empty_results_phrase">
            <p>No ingested records were found matching your query</p>
          </div>
        <% end %>


        <% unless @search_iterator.nil? %>
          <% unless @search_iterator.empty? %>

              <table cellpadding="5" border="1">
                  <tr>
                      <th>Results #</th>
                      <th>Concept_ID</th>
                      <th>Revision_ID</th>
                      <th>ShortName</th>
                  </tr>



                <% @search_iterator.each_with_index do |result, index| %>
                  <tr concept_id="<%= result.concept_id %>" revision_id="<%= result.revision_id %>" onclick="appendRecordsList(this)" class="report_search_row">
                      <td><%= (params[:curr_page].to_i - 1) * 10 + index + 1 %></td>
                      <td id="concept<%= index.to_s %>"><%= result.concept_id %></td>
                      <td id="revision<%= index.to_s %>"><%= result.revision_id %></td>
                      <td><%= result.short_name %></td>
                  </tr>
                <% end %>
              </table>

              <script type="text/javascript">
                var records = [];

                function appendRecordsList(tr_element) {
                  var concept_id = tr_element.getAttribute("concept_id");
                  if (list_contains_record(records, concept_id)) {
                    records = records.filter(function(record) { return record != concept_id });
                      tr_element.style.backgroundColor = "";
                  } else {
                    records.push(concept_id);
                    tr_element.style.backgroundColor = "#CAE4F5";
                  }
                }

                function list_contains_record(list, concept_id) {
                  var temp_records = list.filter(function(record_arr) { return record_arr[0] == concept_id })
                  return temp_records.length > 0
                }
              </script>



              <script type="text/javascript">
                  var selectButton = document.getElementById("select_submit");
                  selectButton.onclick = function() {
                    document.getElementById("records_holder").value = records;
                    document.getElementById("select_form").submit();
                  }
              </script>
          <% end %>
        <% end %>
      </div>
    <% end %>
</div>

app/views/reports/single.csv.erb
<%= CSV.generate_line(["CMR Single Record Report"]) %>

<%= CSV.generate_line(["Concept Id", "Short Name", "DAAC", "Review Close Date"]) %>
<%= CSV.generate_line([@record.concept_id.partition('-').first, @record.short_name, @record.daac, @record.formatted_closed_date]).html_safe %>
<%= CSV.generate_line(["Reviewer", "Date of Review"]) %>
<% @record.reviews.each do |review| %>
  <%= CSV.generate_line([review.reviewer_email, review.formatted_date]).html_safe %>
<% end %>

<% ["red", "yellow", "blue"].each do |color| %>
  <%= CSV.generate_line(["#{color.capitalize} Flagged Elements", "Element", "Value", "Recommendation", "Script Result"]) %>
  <% record_data_colors(@record, color).each do |element| %>
    <%= CSV.generate_line([nil, element.column_name, element.value, element.recommendation, element.script_comment]).html_safe %>
  <% end %>
<% end %>